name: 'upsert issue'
description: 'Create or update an issue with a comment from a file input or a path to a (readme) file'
author: 'siilarsi'
inputs:
  title:
    description: The title of the issue to create or update, mandatory if creating a new issue
  body:
    description: The content of the issue to create or update
  repository:
    description: The repository "owner/repo" for the issue
    default: ${{ github.repository }}
  issue_number:
    description: The issue to update if not provided a new issue will be created
  token:
    description: the token to be used for creating the issue, defaults to the local repositorys token
    default: ${{ github.token }}
outputs:
  github_response_body:
    description: the response body returned from the GitHub API when creating an issue or issue comment
runs:
  using: 'node12'
  main: 'dist/index.js'
