name: 'build-test'
on:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create issue with title
        id: issue_create
        uses: ./
        with:
          title: some title
      - name: output response from issue create
        run: |
          cat <<EOM
          ${{ toJson(steps.issue_create.outputs.github_response_body) }}
          EOM
          sleep 2
      - name: update issue with body
        id: issue_update
        env:
          issue_number: ${{ fromJson(steps.issue_create.outputs.github_response_body).data.number }}
        uses: ./
        with:
          body: some body
          issue_number: ${{ env.issue_number }}
      - name: output response from issue update
        run: |
          cat <<EOM
          ${{ toJson(steps.issue_update.outputs.github_response_body) }}
          EOM

